### ISSUE TITLE
Request: add away-state condition card

### ISSUE THREAD

**Issue by irritanterik** [athombv/nl.thermosmart#10]
I want to pause my thermosmart when the garden doors are open for more than a minute, and unpause it when the doors close.
I only want to unpause the thermosmart when the program was active before.
For this use case, i need a condition card. Something like 'Thermosmart is (not) paused'.
Also 'Thermosmart is (not) paused' trigger cards and a global pause state tag would be very welcome.

**Comment by irritanterik** [comment]
And please shorten poll interval to once a minute.

**Comment by WeeJeWel** [comment]
Fixed in #6590bb0d13f8c9ccf30943e1284c8c77c489f021

Polling is redundant - all changes should be known by webhooks.

**Comment by irritanterik** [comment]
Nice. Thanks!
