### ISSUE TITLE
Set the temperature using a tag

### ISSUE THREAD

**Issue by camilleversteeg** [athombv/nl.thermosmart#11]
Hi guys,

Could you build the feature to set the temperature of the Thermosmart according to a tag. Currently I have alexa setting the temperature, but I need for each single degree a flow. 

![schermafbeelding 2017-05-08 om 20 23 19](https://cloud.githubusercontent.com/assets/15101655/25819238/a35a40a4-342d-11e7-9c22-903a2b7d9fbc.png)

So I have now 10 flows of these, for each degree (15,16,17,18 etc.) a flow. It would be easier if I would just drag the tag there. 

(btw. having an Alexa skill would be cooler)

**Comment by WeeJeWel** [comment]
You should be able to drag the tag on the temperature slider.

**Comment by camilleversteeg** [comment]
@WeeJeWel hi, i can not drag it. It doesn't show an icon to drop it. Maybe because its 'text' and it requires an number? The set the temperature shows a slider. I tried dropping it, but nothing happens. 

![schermafbeelding 2017-05-08 om 20 54 45](https://cloud.githubusercontent.com/assets/15101655/25820203/c4b2bb3e-3430-11e7-961f-18f4521fa155.png)

**Comment by camilleversteeg** [comment]
On this macbook air, when I select the tag, it shows all the dropable zones. But the slider is not blinking like the other zones.

**Comment by camilleversteeg** [comment]
Sorry for the spam, I just tried a number-tag and that seems to be working. Now I have to figure out how to convert the text to a number.

**Comment by WeeJeWel** [comment]
Ah, that makes sense. You can convert it to a number using a Logic card in
the then column.

**Comment by camilleversteeg** [comment]
@WeeJeWel No I can't, when I try to set a Numeric value. I can also not drag the text tag into the value.

**Comment by camilleversteeg** [comment]
@WeeJeWel btw. a good idea would be to display the dropzones RED when you drag a tag that can't be dropped in a certain location. That way you have some feedback as a user.
