### ISSUE TITLE
Thermosmart webhook not working, app runs on polling only

### ISSUE THREAD

**Issue by Dijker** [athombv/nl.thermosmart#12]
Homey 1.5.3 and Thermosmart app 1.0.8
I Wanted to check some internal data and only see Homey is updated with Thermosmart data at the 15 minutes polling interval. The programmed webhook doesn't function.

This prevents me from fe triggering on set temperature changes.

**Comment by WeeJeWel** [comment]
This is a problem on the Thermosmart side. I have contacted the developers.

**Comment by bvdbos** [comment]
![2017-10-26 21_05_02- 91 zones devices - homey](https://user-images.githubusercontent.com/1064079/32072078-a3391a4c-ba91-11e7-9034-c6e6e47e3517.png)
with thermosmart 2.0.2, does everyone have this?

**Comment by WeeJeWel** [comment]
I did not get a response from the developers. I'm closing this issue as it will be automatically fixed whenever they do so.
