### ISSUE TITLE
[Documentation][Sideloading] What to do to Sideload/develop for this app.

### ISSUE THREAD

**Issue by Dijker** [athombv/nl.thermosmart#16]
I am looking to get this App working to extend functionality. 

To get the App working with an working Webhook you need to do the following:
(Without this most of the App looks working but without a functioning webhook!)
 
- Create an Webhook for Thermosmart (https://developer.athom.com/webhooks)
- Configure the WebHook (Edit) with the code from WeeJeWel below as Parser (JavaScript): 
- Apply for an Thermosmart Connect API ID (and fill in your WebHook URL)
- When you got the fork, create a env.json in the root and place the secrets in it like te example below.

Still one Questions: 
? Should I remove and repair the Thermostats switching from the AppStore version and/or switching back to the AppStore version from my own Development Fork ? 
(Will update When I tested it)

Sideload your app and happy developing!!!

```
-=-=- Example env.json -=-=-
{
    "CLIENT_ID": "api-xxx-deadbeef4agee412",
    "CLIENT_SECRET": "abcdef1234567890abcdef12",
    "WEBHOOK_ID": "1234567890abcdef12345678",
    "WEBHOOK_SECRET": "deaf0001000bad010012345678901234" 
}
-=-=- [eof] -=-=-
```

**Comment by WeeJeWel** [comment]
Webhook code:

```
if( Array.isArray(homey_data.thermosmart_id) ) {
  return homey_data.thermosmart_id.indexOf(webhook_data.body.thermostat) > -1;
} else {
	return homey_data.thermosmart_id == webhook_data.body.thermostat;
}
```

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by Dijker** [comment]
With the Webhook Code it works! Thanks!
I didn't have time to test if I Should remove and repair the Thermostat(s) switching from or back to the App Store version. 
but Will close for Now, Thanks for the Help!
