### ISSUE TITLE
Graph Set Target Temperature shows diagonals instead of flat lines

### ISSUE THREAD

**Issue by Dijker** [athombv/nl.thermosmart#2]
**What is your Homey / App version (Settings → System)?**
Version 0.8.24 / Thermosmart 1.0.5.

**What did you try to achieve?**
Read the graph of set temperatures

*Please include detailed steps how we can reproduce the issue*
Look at the insights page and select the target temperature

**What was the result?**
See the graph below with the picture of original Thermosmart graph pasted below.

![image](https://cloud.githubusercontent.com/assets/12412734/14076759/1a0bf8b6-f4e5-11e5-8304-be8faa907ab0.png)

**What did you expect as result?**
Homey Insights records only the changes of the set temperature. It records the date/time it detects the change and it draws diagonals (the green lines ) from point to point. This is incorrect as the set target temperature the minute before each change was the old value. 
I expect flat lines like the black I have  drawn and like they are in the Thermosmart app.
Better would be to record the old value again on detecting each change and record the changed value a second later. 

**Any other remarks**
nope

**Comment by WeeJeWel** [comment]
Try selection the step line graph type to get your desired result! Those
are the flat lines with dots.

**Comment by Dijker** [comment]
Hi Emile,
I already tried all other views but they don't look like what I expect. There are only 4 or 6 new points in a day. (at least if I am not playing with it ;-) ) 
Only dots at the corners of the new set target temperature don't give much information in the nice detailed graph of the measured temperature. 
There are no flat lines is the graph. A "step line" graph where  each dot is a starting point for a horizontal line up to the time of the next measurement/recording would be nice (the verticals would not have to be drawn.)

**Comment by WeeJeWel** [comment]
![screen shot 2016-03-28 at 15 19 07](https://cloud.githubusercontent.com/assets/319873/14078798/f22621c8-f4f8-11e5-963f-9838ae0b87d9.png)

This is what I'm using. Isn't that enough for your needs?

**Comment by Dijker** [comment]
Hi Emile, 
Yep, Thanks! that is exactly what I am looking for.... 
(actually for the target temperature, for the measured temperature I like the default line graph! )
but where do I find it? (maybe 0.8.24+1 ? ;-) )

And maybe for on your verry verry long todo list: is it possible to set a default preferred view or remember the last one? Would be nice....

![image](https://cloud.githubusercontent.com/assets/12412734/14078941/1244091a-f4fa-11e5-885c-5827bac4babe.png)

**Comment by WeeJeWel** [comment]
I think it was introduced in 0.8.25 yeah. Kind of forget what happened when :-)

You can create templates (on top) to save configurations!

**Comment by Dijker** [comment]
Thanks!  nice to see so much progress that things we think of are already fixed in the next release!

**Comment by Dijker** [comment]
v0.8.27 + 1.0.6 App Great !!!
indeed what I expected.

![image](https://cloud.githubusercontent.com/assets/12412734/14215358/b62f4cce-f842-11e5-9545-36a487004c98.png)

**Comment by WeeJeWel** [comment]
Graphs <3
