### ISSUE TITLE
After Re-install Thermosmart app still no measured Temperature in Insights 

### ISSUE THREAD

**Issue by Dijker** [athombv/nl.thermosmart#3]
**What is your Homey / App version (Settings → System)?**
Version 0.8.24 / Thermosmart 1.0.5.

**What did you try to achieve?**
Re-install Thermosmart app from App store after playing with a local modified development-fork of the app. 

*Please include detailed steps how we can reproduce the issue*
Play somewhat around with an modified fork (trying to change the logging behavior).
I am definitely not yet up to development for Homey Apps. 
Cleared the Logs for this app from Insights.
Re-installed the Athom Thermosmart app from the App store. 
Disabled - re-eanbled the app.
Removed Thermosmart Device (de-authorized in Thermosmart control panel), removed App, Reboot Homey, Re-installed App and Added Thermosmart again.
 
**What was the result?**
After testing I did'n get updates from the measured temperature, 
So I reverted back to "default" as described above but this doesn't fix it.
Removing and re-adding the Thermosmart works except from the Insights where the (measured) temperature is missing, although the target temperature is available.
![image](https://cloud.githubusercontent.com/assets/12412734/14077728/0627eb5c-f4ef-11e5-94a7-27d72734aa53.png)

**What did you expect as result?**
That removing and re-installing the app should fix everything I maybe eventually broke ;-)

**Any other remarks**
I have to learn more about this server-side JavaScript ... 
I don't want to break things I want to help fix them ;-)

**Comment by WeeJeWel** [comment]
The measured temperate is only logged when it's actually changed. Try making it hotter and colder in your room :-)

**Comment by Dijker** [comment]
Yes I know and I already waited a couple hours before reporting.... 
but I like the very detailed graph reports always several times (4 - 9 times / hour) a  nice detailed 1 decimal temp. 
That was a nice try for next Friday, 
but I think I broke something in the Homey - Thermosmart configuration  ;-( 
Do you want a me to send a Log?

**Comment by WeeJeWel** [comment]
Hm, I'll investigate. It seems my thermostat has stopped reporting the temperature as well. Could be a broken webhooks server @ Thermosmart.

**Comment by Dijker** [comment]
Thanks! 
Looks it is Fixed in your Easter update 1.0.6
