### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.thermosmart#4]
app v1.0.6 with homey 0.8.27:
In "Zones&Devices" no measured and no set temperature is showing, also in insights no new data is shown. After a reboot new data is downloaded and temperature is showing so the app crashed. 

Sat Apr 02 2016 15:11:35 GMT+0200 (CEST),18.4
Sat Apr 02 2016 15:11:50 GMT+0200 (CEST),18.6
Sat Apr 02 2016 19:47:59 GMT+0200 (CEST),18.6
Sat Apr 02 2016 19:50:41 GMT+0200 (CEST),18.8

**Comment by Dijker** [comment]
I have seen te same issue today!

**Comment by irritanterik** [comment]
![image](https://cloud.githubusercontent.com/assets/15232724/14229409/7cfcffae-f933-11e5-83df-e84ec66e1aff.png)

**Comment by WeeJeWel** [comment]
Can't reproduce this. Please paste the failed network request Response (should have status 500 and red) from the Chrome console Network tab

**Comment by irritanterik** [comment]
console:
![image](https://cloud.githubusercontent.com/assets/15232724/14250136/56a9b9dc-fa7d-11e5-8df2-aa3c89cdbfb8.png)

network request
![image](https://cloud.githubusercontent.com/assets/15232724/14250165/78ae3df0-fa7d-11e5-9475-652d0a40f64b.png)

*no response*

Request is pending a long time:
![image](https://cloud.githubusercontent.com/assets/15232724/14250279/f5c9ce12-fa7d-11e5-8a70-1425670c269c.png)

Set target temperature PUT commands are also pending for a long time before they time-out:
![image](https://cloud.githubusercontent.com/assets/15232724/14250308/19f24e36-fa7e-11e5-866f-d242359edb62.png)

**Comment by bvdbos** [comment]
ical to voice also stopped working (worked last night, not this morning) so I assume this has to do with getting data from the internets. This might also be the reason for the behaviour of sunset/sunrise and other comparable issues.

**Comment by bvdbos** [comment]
log: 7829E39A35
both Thermosmart and Ical to Voice stopped working.

**Comment by bvdbos** [comment]
With 0.8.30 this didn't happen anymore for me...

**Comment by bvdbos** [comment]
Also with 0.8.32 this works for me. @irritanterik and @Dijker, can I close this?

**Comment by irritanterik** [comment]
yes. it's stable now.
Op 10 mei 2016 18:08 schreef "Bas van den Bosch" <notifications@github.com>:

**Comment by Dijker** [comment]
I haven't seen this kind of problems recent. Please close!
