### ISSUE TITLE
slider is really annoying

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.thermosmart#5]
You can set temperature with the slider but it's really annoying to use. Sliding up sets temperature 0,5 degree higher. As the presets "anti-freeze", "away from home", "at home" and "comfort" can't be set-started with Homey, you can only use Homey (or Homey's android app) to adjust the temperature a bit. I would drop the slider here and make it two push-buttons (0,5 degree up and 0,5 degree down).

**Comment by bvdbos** [comment]
The slider has improved a lot, closing this one...

**Comment by WeeJeWel** [comment]
Good to hear! :)
