### ISSUE TITLE
presets not selectable

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.thermosmart#6]
With Homey the presets "anti-freeze", "away from home", "at home" and "comfort" can't be set/started. I'd like to a flow "leave home" to set the temperature to the preset "away from home".

**Comment by Dijker** [comment]
afaik this is not possible as the Thermosmart also cant be set to any of what you call presets. 

If you want to keep running the normal schedule, you can change the set-target-temperature for the current scheduled block to for example 23C  (fe 12u00 to 17u30 = Not-Home = 16C ) 
That is what Homey also can do (although I don't like she slider, pls use an normal entry field.)
If I set the new target-temperature at 17u25 to 20C and the next block is 17u30 => AntiFreeze it will switch 5 min. later to any freeze.

For the Thermosmart it is only possible to change the exceptions in the calendar/agenda for the last half/hour just passed til (some point in time rouded to 15 min. with a minimum of 1 hour later) with an preset. 

although is could be possible to program the app on Homey to put exceptions in the Thermosmart  Agenda by using the API Thermosmart provides, I think it will be difficult to use in programming with flows. You need a flowcard with the preset, a starting time and an ending time. 
That will only work if there is not already a exception in the Termosmart Agenda during that time.

**Comment by bvdbos** [comment]
I think you are right, setting presets on the Thermosmart-app is only possible through the calendar. So it's something missing from the Thermosmart-app which can be accomplished using flows in Homey :+1:
