### ISSUE TITLE
Icon Missing in My Thermosmart Settings page

### ISSUE THREAD

**Issue by Dijker** [athombv/nl.thermosmart#7]
Not specific the App but the integration:
Homeys Icon is missing loged on to ThermoSmart: 
https://my.thermosmart.com/ui#settings

Picture refers to: 
http://athom.nl/wordpress/wp-content/themes/athom/img/logo.png

![image](https://cloud.githubusercontent.com/assets/12412734/16623237/69cdb1da-439d-11e6-8ab2-3e7c36e96975.png)

**Comment by bvdbos** [comment]
![2017-02-04 12_44_49-thermosmart](https://cloud.githubusercontent.com/assets/1064079/22618256/c175f000-ead7-11e6-90fe-46b73a1b2a68.png)
works for me...

**Comment by WeeJeWel** [comment]
Ah this is fixed a while ago!
