### ISSUE TITLE
Pair mislukt: oauth werkt niet

### ISSUE THREAD

**Issue by irritanterik** [athombv/nl.thermosmart#8]
Bij het toevoegen van een themosmart kom ik niet door pairing heen.
Het scherm blijft wit:
![image](https://cloud.githubusercontent.com/assets/15232724/19538162/1b69ab9e-9653-11e6-92bc-c18f93fd051d.png)

Geen fouten te zien in de browser console.

**Comment by WeeJeWel** [comment]
Wordt er wellicht een popup geblokkeerd?

**Comment by irritanterik** [comment]
Dat was het!
